import React, { useMemo, useState } from 'react';
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import { ArrowDownLeft, ArrowUpRight, BarChart3, Check, ChevronDown, CreditCard, DollarSign, Plus, Trash2, Wallet, X } from 'lucide-react-native';
import { VictoryAxis, VictoryBar, VictoryChart, VictoryPie, VictoryTheme } from 'victory-native';

const colors = { ink: '#0B1220', panel: '#111B2E', muted: '#8D9AB3', line: '#25324A', mint: '#65D6A5', coral: '#FF7C82', sky: '#72B9FF', white: '#F7FAFF' };
const categories = ['Operacional', 'Pessoal', 'Marketing', 'Moradia', 'Transporte', 'Alimentação'];
const initialTransactions = [
  { id: '1', description: 'Contrato mensal — Acme Co.', category: 'Operacional', type: 'receita', amount: 12800, status: 'pago', date: 'Hoje', responsible: 'Você' },
  { id: '2', description: 'Folha de pagamento', category: 'Pessoal', type: 'despesa', amount: 4800, status: 'pago', date: 'Ontem', responsible: 'Financeiro' },
  { id: '3', description: 'Campanha de aquisição', category: 'Marketing', type: 'despesa', amount: 1250, status: 'pendente', date: '18/09/2026', responsible: 'Marina' },
  { id: '4', description: 'Projeto Atlas — parcela 2', category: 'Operacional', type: 'receita', amount: 6200, status: 'pendente', date: '22/09/2026', responsible: 'Você' },
  { id: '5', description: 'Aluguel do escritório', category: 'Moradia', type: 'despesa', amount: 2100, status: 'pago', date: '05/09/2026', responsible: 'Financeiro' },
];
const money = (n) => n.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

function IconButton({ icon: Icon, onPress, label, danger }) { return <Pressable accessibilityLabel={label} onPress={onPress} className="h-10 w-10 items-center justify-center rounded-xl" style={{ backgroundColor: danger ? '#3A202B' : colors.line }}><Icon size={18} color={danger ? colors.coral : colors.white} /></Pressable>; }
function Metric({ icon: Icon, label, value, tone = colors.mint }) { return <View className="mb-3 flex-1 rounded-2xl p-4" style={{ backgroundColor: colors.panel, minWidth: '46%' }}><View className="mb-4 h-9 w-9 items-center justify-center rounded-xl" style={{ backgroundColor: `${tone}22` }}><Icon size={18} color={tone} /></View><Text className="text-xs" style={{ color: colors.muted }}>{label}</Text><Text className="mt-1 text-xl font-bold" style={{ color: colors.white }}>{value}</Text></View>; }
function Badge({ status }) { const paid = status === 'pago'; return <View className="rounded-full px-2.5 py-1" style={{ backgroundColor: paid ? '#173A32' : '#3B3020' }}><Text className="text-[11px] font-semibold" style={{ color: paid ? colors.mint : '#F5C56B' }}>{paid ? 'Pago' : 'Pendente'}</Text></View>; }

export default function FinanceiroScreen() {
  const [transactions, setTransactions] = useState(initialTransactions);
  const [period, setPeriod] = useState('Este mês');
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ description: '', amount: '', category: categories[0], type: 'despesa', status: 'pendente' });
  const metrics = useMemo(() => { const receitas = transactions.filter(t => t.type === 'receita' && t.status === 'pago').reduce((s, t) => s + t.amount, 0); const despesas = transactions.filter(t => t.type === 'despesa' && t.status === 'pago').reduce((s, t) => s + t.amount, 0); const receber = transactions.filter(t => t.type === 'receita' && t.status !== 'pago').reduce((s, t) => s + t.amount, 0); const pagar = transactions.filter(t => t.type === 'despesa' && t.status !== 'pago').reduce((s, t) => s + t.amount, 0); return { receitas, despesas, saldo: receitas - despesas, receber, pagar }; }, [transactions]);
  const categoryData = categories.map((x) => ({ x, y: transactions.filter(t => t.category === x).reduce((s, t) => s + t.amount, 0) })).filter(x => x.y);
  const addTransaction = () => { const amount = Number(form.amount.replace(',', '.')); if (!form.description.trim() || !amount || amount <= 0) return Alert.alert('Dados incompletos', 'Informe uma descrição e um valor válido.'); setTransactions([{ id: Date.now().toString(), ...form, amount, date: 'Hoje', responsible: 'Você' }, ...transactions]); setForm({ ...form, description: '', amount: '' }); setShowForm(false); };
  const markPaid = (id) => setTransactions(transactions.map(t => t.id === id ? { ...t, status: 'pago' } : t));
  const remove = (id) => Alert.alert('Excluir lançamento?', 'Essa ação não pode ser desfeita.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: () => setTransactions(transactions.filter(t => t.id !== id)) }]);

  return <SafeAreaView className="flex-1" style={{ backgroundColor: colors.ink }}><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 36 }} showsVerticalScrollIndicator={false}>
    <View className="mb-6 flex-row items-center justify-between"><View><Text className="text-xs font-semibold uppercase tracking-widest" style={{ color: colors.mint }}>Nexus Finance</Text><Text className="mt-2 text-3xl font-bold" style={{ color: colors.white }}>Saúde financeira</Text><Text className="mt-1 text-sm" style={{ color: colors.muted }}>Acompanhe seu dinheiro com clareza.</Text></View><View className="h-12 w-12 items-center justify-center rounded-2xl" style={{ backgroundColor: colors.mint }}><Wallet size={23} color={colors.ink} /></View></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mb-5"><View className="flex-row gap-2">{['Hoje', '7 dias', '30 dias', 'Este mês', 'Todo período'].map(x => <Pressable key={x} onPress={() => setPeriod(x)} className="rounded-full px-4 py-2.5" style={{ backgroundColor: period === x ? colors.mint : colors.panel }}><Text className="text-xs font-semibold" style={{ color: period === x ? colors.ink : colors.muted }}>{x}</Text></Pressable>)}</View></ScrollView>
    <View className="mb-2 flex-row flex-wrap justify-between"><Metric icon={ArrowUpRight} label="Receitas efetivas" value={money(metrics.receitas)} /><Metric icon={ArrowDownLeft} label="Despesas pagas" value={money(metrics.despesas)} tone={colors.coral} /><Metric icon={DollarSign} label="Saldo líquido" value={money(metrics.saldo)} tone={colors.sky} /><Metric icon={CreditCard} label="A receber / pagar" value={`${money(metrics.receber)} / ${money(metrics.pagar)}`} tone="#F5C56B" /></View>
    <View className="mb-4 rounded-2xl p-4" style={{ backgroundColor: colors.panel }}><View className="mb-1 flex-row items-center gap-2"><BarChart3 size={18} color={colors.mint} /><Text className="font-bold" style={{ color: colors.white }}>Receitas vs despesas</Text></View><Text className="mb-2 text-xs" style={{ color: colors.muted }}>Visão resumida de {period.toLowerCase()}</Text><VictoryChart height={210} width={350} theme={VictoryTheme.material} domainPadding={24} padding={{ top: 15, bottom: 30, left: 48, right: 20 }}><VictoryAxis style={{ axis: { stroke: colors.line }, tickLabels: { fill: colors.muted, fontSize: 9 } }} /><VictoryBar data={[{ x: 'Sem 1', y: metrics.receitas * .35 }, { x: 'Sem 2', y: metrics.receitas * .22 }, { x: 'Sem 3', y: metrics.receitas * .48 }, { x: 'Sem 4', y: metrics.receitas * .7 }]} style={{ data: { fill: colors.mint, width: 14 } }} /><VictoryBar data={[{ x: 'Sem 1', y: metrics.despesas * .5 }, { x: 'Sem 2', y: metrics.despesas * .3 }, { x: 'Sem 3', y: metrics.despesas * .65 }, { x: 'Sem 4', y: metrics.despesas * .4 }]} style={{ data: { fill: colors.coral, width: 14 } }} /></VictoryChart></View>
    <View className="mb-4 rounded-2xl p-4" style={{ backgroundColor: colors.panel }}><Text className="mb-2 font-bold" style={{ color: colors.white }}>Distribuição por categoria</Text><View className="items-center"><VictoryPie width={230} height={190} data={categoryData} colorScale={[colors.mint, colors.sky, '#F5C56B', colors.coral, '#B79CFF', '#8DE2D1']} innerRadius={52} labelRadius={82} style={{ labels: { fill: colors.white, fontSize: 9 } }} /></View><View className="flex-row flex-wrap justify-center gap-x-4 gap-y-2">{categoryData.slice(0, 4).map((x, i) => <View key={x.x} className="flex-row items-center gap-1"><View className="h-2 w-2 rounded-full" style={{ backgroundColor: [colors.mint, colors.sky, '#F5C56B', colors.coral][i] }} /><Text className="text-xs" style={{ color: colors.muted }}>{x.x}</Text></View>)}</View></View>
    <View className="mb-3 flex-row items-center justify-between"><Text className="text-xl font-bold" style={{ color: colors.white }}>Transações</Text><Pressable onPress={() => setShowForm(true)} className="flex-row items-center gap-2 rounded-xl px-3 py-2.5" style={{ backgroundColor: colors.mint }}><Plus size={16} color={colors.ink} /><Text className="text-xs font-bold" style={{ color: colors.ink }}>Lançamento</Text></Pressable></View>
    {transactions.map(t => <View key={t.id} className="mb-3 rounded-2xl p-4" style={{ backgroundColor: colors.panel }}><View className="flex-row items-start justify-between"><View className="flex-1 pr-3"><Text className="font-semibold" style={{ color: colors.white }}>{t.description}</Text><Text className="mt-1 text-xs" style={{ color: colors.muted }}>{t.category} · {t.date} · {t.responsible}</Text></View><Badge status={t.status} /></View><View className="mt-4 flex-row items-center justify-between"><Text className="text-lg font-bold" style={{ color: t.type === 'receita' ? colors.mint : colors.coral }}>{t.type === 'receita' ? '+' : '-'} {money(t.amount)}</Text><View className="flex-row gap-2">{t.status !== 'pago' && <IconButton icon={Check} label="Marcar como pago" onPress={() => markPaid(t.id)} />}<IconButton icon={Trash2} label="Excluir transação" danger onPress={() => remove(t.id)} /></View></View></View>)}
  </ScrollView>
  <Modal visible={showForm} transparent animationType="slide" onRequestClose={() => setShowForm(false)}><View className="flex-1 justify-end" style={{ backgroundColor: '#00000088' }}><View className="rounded-t-3xl p-6" style={{ backgroundColor: colors.ink }}><View className="mb-6 flex-row items-center justify-between"><Text className="text-2xl font-bold" style={{ color: colors.white }}>Novo lançamento</Text><IconButton icon={X} label="Fechar" onPress={() => setShowForm(false)} /></View><Text className="mb-2 text-xs font-semibold" style={{ color: colors.muted }}>TIPO</Text><View className="mb-4 flex-row gap-2">{['despesa', 'receita'].map(type => <Pressable key={type} onPress={() => setForm({ ...form, type })} className="flex-1 rounded-xl p-3" style={{ backgroundColor: form.type === type ? (type === 'receita' ? '#173A32' : '#3A202B') : colors.panel }}><Text className="text-center font-semibold" style={{ color: type === 'receita' ? colors.mint : colors.coral }}>{type === 'receita' ? 'Receita' : 'Despesa'}</Text></Pressable>)}</View><TextInput placeholder="Descrição" placeholderTextColor={colors.muted} value={form.description} onChangeText={description => setForm({ ...form, description })} className="mb-3 rounded-xl px-4 py-3" style={{ backgroundColor: colors.panel, color: colors.white }} /><TextInput placeholder="Valor (ex.: 1250,00)" placeholderTextColor={colors.muted} keyboardType="decimal-pad" value={form.amount} onChangeText={amount => setForm({ ...form, amount })} className="mb-3 rounded-xl px-4 py-3" style={{ backgroundColor: colors.panel, color: colors.white }} /><Pressable onPress={() => setForm({ ...form, category: categories[(categories.indexOf(form.category) + 1) % categories.length] })} className="mb-5 flex-row items-center justify-between rounded-xl px-4 py-3" style={{ backgroundColor: colors.panel }}><Text style={{ color: colors.white }}>{form.category}</Text><ChevronDown size={18} color={colors.muted} /></Pressable><Pressable onPress={addTransaction} className="rounded-xl py-4" style={{ backgroundColor: colors.mint }}><Text className="text-center font-bold" style={{ color: colors.ink }}>Salvar lançamento</Text></Pressable></View></View></Modal></SafeAreaView>;
}
